apiVersion: v1
kind: Service
metadata:
  name: devsecops-svc
  labels:
    app: devsecops
spec:
  selector:
    app: devsecops
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: NodePort
